name: mlops-env
channels:
  - conda-forge
  - defaults

dependencies:
  # Python compatível com MLflow + TensorFlow
  - python=3.10
  - pip
  - git
  - curl

  # Pacotes científicos
  - numpy=1.26.4
  - pandas=2.2.3
  - matplotlib
  - scikit-learn=1.5.2

  # Jupyter
  - jupyterlab

  # Pip
  - pip:
      - -r requirements.txt